const COLOR_JACARTA = '#3F375E'
const COLOR_PERANO = '#A9AEEA'
const COLOR_SAN_MARINO = '#546B9F'
const COLOR_PERFUME = '#BEA7E6'
const COLOR_WISTFUL = '#9F9AD4'
const COLOR_PURPLE_MOUNTAIN_S_MAJESTY = '#947EAB'
export const colors = {
  COLOR_JACARTA,
  COLOR_PERANO,
  COLOR_SAN_MARINO,
  COLOR_PERFUME,
  COLOR_WISTFUL,
  COLOR_PURPLE_MOUNTAIN_S_MAJESTY,
}
